function [fitresult, gof] = createFit7(x, y)
%CREATEFIT7(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Mar-2019 14:35:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*exp(-k*x^n)+b*exp(-g*x)+c*exp(-h*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.634413158611661 0.462679877934471 0.19025783695121 0.959492426392903 0.655740699156587 0.141886338627215 0.421761282626275];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Moisture Ratio Vs Time', 'Henderson and Pabis', 'Location', 'NorthEast' );
% Label axes
xlabel Time
ylabel MR
xlim([8,17])
grid on


