function [fitresult, gof] = createFit(m, l)
%CREATEFIT(M,L)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : m
%      Y Output: l
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Feb-2019 13:43:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( m, l );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.917496175864885 0.995645810718987 0.800281133681857];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'moisture ratio v/s time', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel Time
ylabel Moisture Ratio
grid on


